server:
  port: 8081
spring:
  application:
    name: course-service
  datasource:
    #url: jdbc:mysql://db-service:3306/db-3it 
    #username: mysql-db-3it
    #password: admin123
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      #defaultZone: http://eureka-service:8761/eureka/
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
    register-with-eureka: true
    fetch-registry: true
  instance:
      instance-id: ${spring.application.name}:${server.port}
      hostname: ${spring.application.name}    

student-service:
  url: http://gateway-server/api/carreras