server:
  port: 8099
spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/institucion
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true