# student-service/src/main/resources/application.yml
spring:
  application:
    name: student-service
  config:
    import: "optional:configserver:http://config-service:8888"
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "refresh,health"

eureka:
    client:
        service-url:
            defaultZone: http://eureka-service:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${server.port}
        hostname: ${spring.application.name}