apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: course-feign-service
  name: course-feign-service
spec:
  ports:
    - name: "course-feign-service"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: course-feign-service
  type: ClusterIP