server:
  port: 8082
spring:
  application:
    name: course-feign-service
  datasource:
    url: jdbc:mysql://localhost:3306/institucion
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
student-service:
  #url: http://gateway-server/api/carreras
  url: http://localhost:8095/api/carreras