apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-03aefd6f5b2a5f3aa, subnet-03f84a2fe39a4652d"  # Cambiar los nombres de las subnets privada de la VPC
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  creationTimestamp: null
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  ports:
    - name: "gateway-service"
      port: 8095
      targetPort: 8095
  selector:
    io.kompose.service: gateway-service
  type: LoadBalancer
