apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: config-service
  name: config-service
spec:
  ports:
    - name: "config-service"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: config-service
  type: ClusterIP